/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				"error-container": "#fe8983",
				"on-tertiary-container": "#326365",
				"surface-container-highest": "#dbe4e7",
				"tertiary": "#366769",
				"tertiary-container": "#cafdff",
				"secondary-dim": "#525354",
				"error": "#9f403d",
				"tertiary-dim": "#295a5d",
				"on-tertiary-fixed": "#1e5153",
				"inverse-on-surface": "#9b9d9e",
				"outline-variant": "#abb3b7",
				"secondary": "#5e5f60",
				"primary-dim": "#3c5377",
				"primary": "#485f84",
				"surface-tint": "#485f84",
				"primary-container": "#d5e3ff",
				"on-secondary-fixed": "#3e4040",
				"tertiary-fixed": "#cafdff",
				"surface-container-lowest": "#ffffff",
				"primary-fixed": "#d5e3ff",
				"primary-fixed-dim": "#bfd5ff",
				"on-surface-variant": "#586064",
				"on-primary": "#f6f7ff",
				"inverse-surface": "#0c0f10",
				"on-error": "#fff7f6",
				"surface-container-low": "#f1f4f6",
				"surface": "#f8f9fa",
				"on-secondary-container": "#505252",
				"surface-container": "#eaeff1",
				"tertiary-fixed-dim": "#bceff1",
				"background": "#f8f9fa",
				"secondary-container": "#e2e2e2",
				"on-primary-fixed": "#294062",
				"on-tertiary-fixed-variant": "#3d6e70",
				"on-tertiary": "#e3feff",
				"on-background": "#2b3437",
				"on-primary-container": "#3c5276",
				"surface-container-high": "#e3e9ec",
				"on-error-container": "#752121",
				"on-primary-fixed-variant": "#465c80",
				"secondary-fixed": "#e2e2e2",
				"surface-bright": "#f8f9fa",
				"error-dim": "#4e0309",
				"on-secondary-fixed-variant": "#5a5c5c",
				"outline": "#737c7f",
				"secondary-fixed-dim": "#d4d4d4",
				"inverse-primary": "#bbd3fd",
				"surface-variant": "#dbe4e7",
				"on-secondary": "#f9f9f9",
				"surface-dim": "#d1dce0",
				"on-surface": "#2b3437"
			},
			fontFamily: {
				"headline": ["Manrope", "sans-serif"],
				"body": ["Inter", "sans-serif"],
				"label": ["Inter", "sans-serif"]
			},
			borderRadius: {
				"DEFAULT": "0.125rem",
				"lg": "0.25rem",
				"xl": "0.5rem",
				"full": "0.75rem"
			},
		},
	},
	plugins: [],
};
